env:
  node: true
  jest: true
extends:
  - eslint:recommended  # use the recommended eslint rules
  - plugin:@typescript-eslint/recommended  # use the recommended rules from the @typescript-eslint/eslint-plugin
  - plugin:@typescript-eslint/recommended-requiring-type-checking  # extra typing rules for TypeScript
  - plugin:prettier/recommended  # enables eslint-plugin-prettier and displays prettier errors as ESLint errors. Make sure this is always the last configuration in the extends array
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  sourceType: module
plugins:
  - '@typescript-eslint'
root: true
rules:
  no-console: warn
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-explicit-any': off
